services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: announcement
      POSTGRES_USER: announcement
      POSTGRES_PASSWORD: announcement123$$

  zitadel:
    restart: "always"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - "ZITADEL_DATABASE_COCKROACH_HOST=crdb"
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_EXTERNALPORT=8081"
    depends_on:
      crdb:
        condition: "service_healthy"
    ports:
      - "8081:8080"

  crdb:
    restart: "always"
    image: "cockroachdb/cockroach:v23.1.13"
    command: "start-single-node --insecure"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    volumes:
      - cockroachdb-data:/cockroach/cockroach-data:rw
    ports:
      - "9090:8080"
      - "26257:26257"

volumes:
  data:
  cockroachdb-data: